const {
    Client,
    GatewayIntentBits,
    EmbedBuilder,
    ActionRowBuilder,
    ButtonBuilder,
    ButtonStyle,
    UserSelectMenuBuilder,
    SlashCommandBuilder,
    ModalBuilder,
    TextInputBuilder,
    TextInputStyle,
    REST,
    Routes,
    ChannelType,
    Partials
} = require('discord.js');

require('dotenv').config();

const client = new Client({
    intents: [
        GatewayIntentBits.Guilds,
        GatewayIntentBits.GuildMessages,
        GatewayIntentBits.DirectMessages,
        GatewayIntentBits.MessageContent
    ],
    partials: [Partials.Channel, Partials.Message]
});

// ============================================
//         STUDIO CONFIGURATION CORE
// ============================================
const CONFIG = {
    GUILD_ID: '1508151252561694861',             
    HIRED_CHANNEL_ID: '1508153883669827757',
    NOT_HIRED_CHANNEL_ID: '1508153941521858680',
    FORUM_CHANNEL_ID: '1509210757248581782',      // Base forum channel for interviews
    DM_FORUM_CHANNEL_ID: '1509987579020447847',   // ✅ Auto-target for bidirectional DM Sessions
    MANAGEMENT_ROLE_ID: 'YOUR_STAFF_ROLE_ID_HERE'   
};

const COLORS = {
    neutral: '#2c2f33',
    success: '#43b581',  
    danger: '#f04747',
    warning: '#faa61a',  
    info: '#7289da'
};

const SYSTEM_CACHE = {
    totalInterviews: 0,
    activeInterviews: 0,
    acceptedCount: 0,
    rejectedCount: 0,
    pendingHires: {}
};

// ============================================
//         VISUAL EMBED TEMPLATES
// ============================================
const TEMPLATES = {
    portfolio_approved: {
        title: '🚀 Portfolio Approved — Next Steps',
        color: COLORS.success,
        description: (user) => `Hello ${user},\n\nThat portfolio was incredibly impressive! We would love to move you forward to the **knowledge evaluation phase** of our application pipeline.\n\nPlease follow the onboarding sequence below to set up your profile:\n\n📋 **Onboarding Protocol**\n1️⃣ Head over to our [Certamen Onboarding Portal](https://emersondhaba.my.canva.site/certamen)\n2️⃣ Locate the **Sign Up** section, fill in your profile details, and apply as an **Applicant**.\n3️⃣ **Log In** to your newly established account.\n4️⃣ Complete the **Welcome Survey** to activate your testing module.`,
        footer: 'Certamen Studios Evaluation Phase',
        hasButton: true
    },
    background_check: {
        title: '📁 Transmission Logged & Filed',
        color: COLORS.warning,
        description: (user) => `Thank you, ${user}. Your survey answers have been compiled cleanly and routed directly to our **Filing Department**.\n\n⚙️ **Background Verification Operations**\nYour comprehensive application performance report is currently being auto-generated by our background core systems.\n\nWhile our administration logs finalize your file updates, **can we proceed with some baseline background checks?**`,
        footer: 'Certamen Studios Security Clearance',
        hasButton: false
    }
};

function generateSmallJobCode() {
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
    let code = '';
    for (let i = 0; i < 4; i++) {
        code += chars.charAt(Math.floor(Math.random() * chars.length));
    }
    return code;
}

// ============================================
//         COMMAND REGISTRATION ENGINE
// ============================================
const commands = [
    new SlashCommandBuilder()
        .setName('interview')
        .setDescription('Open a live-chat forum thread bridge for an applicant with a custom role')
        .addUserOption(option => option.setName('candidate').setDescription('Select target applicant').setRequired(true))
        .addStringOption(option => option.setName('role').setDescription('Type any custom role name (e.g., UI Designer, Animator, GFX)').setRequired(true)),
    new SlashCommandBuilder()
        .setName('dashboard')
        .setDescription('View the live deployment metrics dashboard for HR operations'),
    new SlashCommandBuilder()
        .setName('onboard')
        .setDescription('Manually onboard a candidate outside of an active interview channel workflow')
        .addUserOption(option => option.setName('candidate').setDescription('The user being accepted').setRequired(true))
        .addStringOption(option => option.setName('role').setDescription('Type any custom role name for onboarding').setRequired(true)),
    new SlashCommandBuilder()
        .setName('sendtemplate')
        .setDescription('Dispatch a formal HR portal notification block to the candidate thread')
        .addStringOption(option => option.setName('template')
            .setDescription('Select the layout frame template')
            .setRequired(true)
            .addChoices(
                { name: 'Portfolio Approved (Step 1)', value: 'portfolio_approved' },
                { name: 'Background Verification (Step 2)', value: 'background_check' }
            ))
        .addUserOption(option => option.setName('candidate').setDescription('The candidate to address in the embed greeting').setRequired(true)),
    new SlashCommandBuilder()
        .setName('dm_session')
        .setDescription('Start a bidirectional DM session thread inside the dedicated forum channel')
        .addUserOption(option => option.setName('target').setDescription('Select the user to open a live stream with').setRequired(true))
        .addStringOption(option => option.setName('message').setDescription('Type your introductory message').setRequired(true))
        .addAttachmentOption(option => option.setName('image').setDescription('Upload an optional image').setRequired(false)),
    new SlashCommandBuilder()
        .setName('dm_one_way')
        .setDescription('Send an unmonitored one-way DM message card and log it inside a custom channel')
        .addUserOption(option => option.setName('target').setDescription('Select the user to send a DM to').setRequired(true))
        .addStringOption(option => option.setName('message').setDescription('Type your message content').setRequired(true))
        .addChannelOption(option => option.setName('log_channel').setDescription('Select the channel to log the copy card inside').setRequired(true)
            .addChannelTypes(ChannelType.GuildText))
        .addAttachmentOption(option => option.setName('image').setDescription('Upload an optional image').setRequired(false))
];

const rest = new REST({ version: '10' }).setToken(process.env.TOKEN);

client.once('ready', async () => {
    console.log(`✨ ${client.user.tag} Online. Syncing application commands...`);
    try {
        await rest.put(
            Routes.applicationGuildCommands(client.user.id, CONFIG.GUILD_ID), 
            { body: commands }
        );
        console.log('✅ Instant guild deployment completed successfully to server 1508151252561694861.');
    } catch (error) {
        console.error('❌ Sync failed:', error);
    }
});

// ============================================
//       CENTRAL INTERACTION ENGINE CORE
// ============================================
client.on('interactionCreate', async interaction => {
    
    if (interaction.isChatInputCommand()) {
        
        // ----------------------------------------
        // 1. BIDIRECTIONAL DM SESSION (WITH LIVE THREAD REPLIES)
        // ----------------------------------------
        if (interaction.commandName === 'dm_session') {
            await interaction.deferReply({ ephemeral: true });

            const targetUser = interaction.options.getUser('target');
            const messageText = interaction.options.getString('message');
            const imageAttachment = interaction.options.getAttachment('image');

            const dmEmbed = new EmbedBuilder()
                .setColor(COLORS.info)
                .setAuthor({ name: 'Message from Certamen Studios HR', iconURL: interaction.guild?.iconURL() || client.user.displayAvatarURL() })
                .setDescription(messageText)
                .setTimestamp();

            if (imageAttachment) {
                if (imageAttachment.contentType?.startsWith('image/')) {
                    dmEmbed.setImage(imageAttachment.url);
                } else {
                    return interaction.editReply({ content: '❌ **Error:** Attached file must be a valid image type.' });
                }
            }

            try { await targetUser.send({ embeds: [dmEmbed] }); } catch (error) {
                return interaction.editReply({ content: `❌ **Failed to send DM:** ${targetUser.username} has closed their direct messages.` });
            }

            try {
                const dmForumChannel = await client.channels.fetch(CONFIG.DM_FORUM_CHANNEL_ID);
                const threadName = `[DM] ${targetUser.username}`;

                const threadEmbed = new EmbedBuilder()
                    .setColor(COLORS.success)
                    .setTitle(`📶 Communication Node Connected ── ${targetUser.username}`)
                    .setDescription([
                        '```ansi',
                        '[1;32m[CONNECTED][0m Direct DM pipeline node deployed successfully.',
                        '```',
                        '### 📝 Transmission Rules:',
                        '┌── **Live Tunnel Info**',
                        '├── » *Anything typed right here routes instantly back to their DMs.*',
                        '└── » *Any responses they send to the bot will update right here.*'
                    ].join('\n'))
                    .addFields(
                        { name: '🆔 Core System ID', value: `\`${targetUser.id}\``, inline: true },
                        { name: '✉️ Original Transmission', value: messageText.length > 500 ? `${messageText.slice(0, 500)}...` : messageText }
                    );

                if (imageAttachment) threadEmbed.setImage(imageAttachment.url);

                const thread = await dmForumChannel.threads.create({
                    name: threadName,
                    autoArchiveDuration: 1440,
                    message: {
                        content: `🎯 **DM Log Stream** established for ${targetUser}.`,
                        embeds: [threadEmbed]
                    }
                });

                await interaction.editReply({ content: `✅ **Live Session Tunnel Spawned:** Access here: <#${thread.id}>` });
            } catch (err) {
                console.error(err);
                await interaction.editReply({ content: '⚠️ **DM Sent**, but failed to auto-generate the tracking thread in the forum. Verify bot permissions.' });
            }
            return;
        }

        // ----------------------------------------
        // 2. ONE-WAY DM (NO REPLIES, CUSTOM CHANNEL LOG CARD)
        // ----------------------------------------
        if (interaction.commandName === 'dm_one_way') {
            await interaction.deferReply({ ephemeral: true });

            const targetUser = interaction.options.getUser('target');
            const messageText = interaction.options.getString('message');
            const logChannel = interaction.options.getChannel('log_channel');
            const imageAttachment = interaction.options.getAttachment('image');

            const dmEmbed = new EmbedBuilder()
                .setColor(COLORS.info)
                .setAuthor({ name: 'Message from Certamen Studios HR', iconURL: interaction.guild?.iconURL() || client.user.displayAvatarURL() })
                .setDescription(messageText)
                .setTimestamp();

            if (imageAttachment) {
                if (imageAttachment.contentType?.startsWith('image/')) {
                    dmEmbed.setImage(imageAttachment.url);
                } else {
                    return interaction.editReply({ content: '❌ **Error:** Attached file must be a valid image type.' });
                }
            }

            try { await targetUser.send({ embeds: [dmEmbed] }); } catch (error) {
                return interaction.editReply({ content: `❌ **Failed to send DM:** ${targetUser.username} has closed their direct messages.` });
            }

            try {
                const oneWayLogEmbed = new EmbedBuilder()
                    .setColor(COLORS.neutral)
                    .setTitle('📭 One-Way Outbound Message Dispatched')
                    .setDescription('`⚠️ Note: Replies are completely unmonitored for this message block.`')
                    .addFields(
                        { name: '👤 Recipient', value: `${targetUser} (\`${targetUser.id}\`)`, inline: true },
                        { name: '✍️ Authorized Agent', value: `${interaction.user}`, inline: true },
                        { name: '📝 Content Sent', value: messageText }
                    )
                    .setTimestamp();

                if (imageAttachment) oneWayLogEmbed.setImage(imageAttachment.url);

                await logChannel.send({ embeds: [oneWayLogEmbed] });
                await interaction.editReply({ content: `✅ **One-Way DM Sent Successfully!** Copy receipt logged inside <#${logChannel.id}>.` });
            } catch (err) {
                console.error(err);
                await interaction.editReply({ content: '⚠️ **DM Sent**, but could not log receipt to that channel. Check bot permissions.' });
            }
            return;
        }

        // TEMPLATE DISPATCH LAYER
        if (interaction.commandName === 'sendtemplate') {
            const templateKey = interaction.options.getString('template');
            const candidate = interaction.options.getUser('candidate');
            
            const selectedTemplate = TEMPLATES[templateKey];
            if (!selectedTemplate) return interaction.reply({ content: '❌ Selected template error.', ephemeral: true });

            const now = new Date();
            const timestampString = `${String(now.getDate()).padStart(2, '0')}/${String(now.getMonth() + 1).padStart(2, '0')}/${now.getFullYear()}, ${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`;

            const embed = new EmbedBuilder()
                .setAuthor({ name: 'Certamen Studios — Core Processing Systems', iconURL: interaction.guild?.iconURL() || client.user.displayAvatarURL() })
                .setColor(selectedTemplate.color)
                .setTitle(selectedTemplate.title)
                .setDescription(selectedTemplate.description(candidate.toString()))
                .setFooter({ text: `${selectedTemplate.footer} • ${timestampString}` });

            const components = [];
            if (selectedTemplate.hasButton) {
                const linkButton = new ButtonBuilder()
                    .setLabel('Open Onboarding Website')
                    .setStyle(ButtonStyle.Link)
                    .setURL('https://emersondhaba.my.canva.site/certamen');
                
                components.push(new ActionRowBuilder().addComponents(linkButton));
            }

            await interaction.reply({ embeds: [embed], components: components.length > 0 ? components : undefined });
            return;
        }

        // INTERVIEW SETUP WITH CUSTOM ROLE
        if (interaction.commandName === 'interview') {
            await interaction.deferReply({ ephemeral: true });
            
            const candidate = interaction.options.getUser('candidate');
            const customRole = interaction.options.getString('role').trim();

            try {
                const forumChannel = await client.channels.fetch(CONFIG.FORUM_CHANNEL_ID);
                const threadName = `${candidate.username} - ${customRole.toUpperCase()}`;

                const threadEmbed = new EmbedBuilder()
                    .setColor(COLORS.info)
                    .setTitle(`📶 Network Tunnel Linked ── ${candidate.username}`)
                    .setDescription([
                        '```ansi',
                        '[1;34m[READY][0m Communications routing tunnel configured smoothly.',
                        '```',
                        '### 🛠️ Protocol Infrastructure:',
                        '┌── **Direct Route Instructions**',
                        '├── » *Standard texts typed directly below transfer instantly into user DMs.*',
                        '└── » *Candidate responses are piped directly back to this control feed workspace.*'
                    ].join('\n'))
                    .addFields(
                        { name: '🆔 Core System ID', value: `\`${candidate.id}\``, inline: true },
                        { name: '💼 Assigned Discipline', value: `\`${customRole}\``, inline: true }
                    );

                const encodedRole = Buffer.from(customRole).toString('base64').replace(/=/g, '');

                const actionRow = new ActionRowBuilder().addComponents(
                    new ButtonBuilder().setCustomId(`hire_${candidate.id}_${encodedRole}`).setLabel('Finalize Hire').setStyle(ButtonStyle.Success).setEmoji('✅'),
                    new ButtonBuilder().setCustomId(`deny_${candidate.id}_${encodedRole}`).setLabel('Drop Candidate').setStyle(ButtonStyle.Danger).setEmoji('❌')
                );

                const thread = await forumChannel.threads.create({
                    name: threadName,
                    autoArchiveDuration: 1440,
                    message: {
                        content: `🎙️ **Session Node Online:** Terminal channel built for ${candidate}.`,
                        embeds: [threadEmbed],
                        components: [actionRow]
                    }
                });

                SYSTEM_CACHE.totalInterviews++;
                SYSTEM_CACHE.activeInterviews++;

                try {
                    const welcomeEmbed = new EmbedBuilder()
                        .setColor(COLORS.info)
                        .setAuthor({ name: 'Message from HR (Arya)', iconURL: client.user.displayAvatarURL() })
                        .setDescription(`Hello **${candidate.displayName}**!\n\nI have successfully activated your secure interview communications line. My name is **Arya**, and I will be guiding you through today.\n\nYou can reply directly to this message block at any time!`);
                    await candidate.send({ embeds: [welcomeEmbed] });
                } catch {}

                await interaction.editReply({ content: `✅ **Bridge Built for ${customRole.toUpperCase()}:** Access here: <#${thread.id}>` });
            } catch (err) {
                console.error(err);
                await interaction.editReply({ content: '❌ **Error:** Failed to spin up the forum workspace thread.' });
            }
            return;
        }

        // METRICS DASHBOARD
        if (interaction.commandName === 'dashboard') {
            const dashEmbed = new EmbedBuilder()
                .setColor(COLORS.neutral)
                .setTitle('🖥️ Operational Performance Analytics')
                .setDescription('`📊 Live Network Diagnostics Log` ── Updates Active')
                .addFields(
                    { name: '📥 Active Message Channels', value: `\`▰▰▰▰▱▱▱▱▱▱ 40%\`\n» **${SYSTEM_CACHE.activeInterviews}** Active Sessions`, inline: true },
                    { name: '📦 Cumulative Processed Logs', value: `\`▰▰▰▰▰▰▰▱▱▱ 70%\`\n» **${SYSTEM_CACHE.totalInterviews}** Total Streams`, inline: true }
                );
            return interaction.reply({ embeds: [dashEmbed] });
        }

        // STANDALONE MANUAL ONBOARD
        if (interaction.commandName === 'onboard') {
            const candidate = interaction.options.getUser('candidate');
            const customRole = interaction.options.getString('role').trim();
            const encodedRole = Buffer.from(customRole).toString('base64').replace(/=/g, '');

            const modal = new ModalBuilder()
                .setCustomId(`manualhiremodal_${candidate.id}_${encodedRole}`)
                .setTitle('📝 Enter Performance Score');

            const scoreInput = new TextInputBuilder()
                .setCustomId('metrics_passrate')
                .setLabel('Pass Rate (%)')
                .setStyle(TextInputStyle.Short)
                .setPlaceholder('e.g., 95%')
                .setRequired(true);

            modal.addComponents(new ActionRowBuilder().addComponents(scoreInput));
            await interaction.showModal(modal);
            return;
        }
    }

    // ----------------------------------------
    // HANDLE PANEL INTERACTIVE BUTTONS
    // ----------------------------------------
    if (interaction.isButton()) {
        const parts = interaction.customId.split('_');
        const action = parts[0];
        const targetId = parts[1];
        
        let role = '';
        if (parts[2]) {
            try { role = Buffer.from(parts[2], 'base64').toString('utf8'); } catch { role = parts[2]; }
        }

        if (action === 'deny') {
            await interaction.deferReply({ ephemeral: true });
            let targetUser;
            try { targetUser = await client.users.fetch(targetId); } catch { return; }

            if (SYSTEM_CACHE.activeInterviews > 0) SYSTEM_CACHE.activeInterviews--;
            SYSTEM_CACHE.rejectedCount++;

            const rejectEmbed = new EmbedBuilder()
                .setColor(COLORS.danger)
                .setTitle('Certamen Studios — Application Status Update')
                .setDescription(`Hello **${targetUser.displayName}**,\n\nThank you for taking the time to talk with us. Unfortunately, at this time we have decided not to move forward with your application file.`);

            try { await targetUser.send({ embeds: [rejectEmbed] }); } catch {}

            const logsChan = await client.channels.fetch(CONFIG.NOT_HIRED_CHANNEL_ID).catch(() => null);
            if (logsChan) {
                const visualAuditEmbed = new EmbedBuilder()
                    .setColor(COLORS.danger)
                    .setTitle('🔴 System Repository Compiling Archive')
                    .setDescription('`🔒 Compressing Application Session File Blocks`')
                    .addFields(
                        { name: '👤 Candidate File', value: `${targetUser}\n(${targetUser.username})`, inline: true },
                        { name: '🛠️ Target Role Rejected', value: `\`${role ? role.toUpperCase() : 'UNKNOWN'}\``, inline: true }
                    );
                await logsChan.send({ embeds: [visualAuditEmbed] });
            }

            await interaction.editReply({ content: '🏁 **Candidate denied. Session archived.**' });
            await interaction.channel.setName(`[DENIED] ${targetUser.username}`);
            await interaction.channel.setArchived(true);
            return;
        }

        if (action === 'hire') {
            const encodedRole = Buffer.from(role).toString('base64').replace(/=/g, '');
            const modal = new ModalBuilder()
                .setCustomId(`hiremodal_${targetId}_${encodedRole}`)
                .setTitle('📝 Enter Performance Score');

            const scoreInput = new TextInputBuilder()
                .setCustomId('metrics_passrate')
                .setLabel('Pass Rate (%)')
                .setStyle(TextInputStyle.Short)
                .setPlaceholder('e.g., 94%')
                .setRequired(true);

            modal.addComponents(new ActionRowBuilder().addComponents(scoreInput));
            await interaction.showModal(modal);
            return;
        }
    }

    // ----------------------------------------
    // HANDLE MODAL FORM SUBMISSIONS
    // ----------------------------------------
    if (interaction.isModalSubmit()) {
        if (interaction.customId.startsWith('hiremodal_') || interaction.customId.startsWith('manualhiremodal_')) {
            await interaction.deferReply();
            const isManual = interaction.customId.startsWith('manualhiremodal_');
            const parts = interaction.customId.split('_');
            const targetId = parts[1];
            
            let role = '';
            try { role = Buffer.from(parts[2], 'base64').toString('utf8'); } catch { role = parts[2]; }

            const passRate = interaction.fields.getTextInputValue('metrics_passrate');
            const generatedCode = generateSmallJobCode();
            const cacheKey = isManual ? `manual_${interaction.id}` : interaction.channel.id;

            SYSTEM_CACHE.pendingHires[cacheKey] = {
                targetId,
                role,
                jobCode: generatedCode,
                passRate,
                hrAgent: interaction.user,
                isManual: isManual,
                channel: isManual ? null : interaction.channel
            };

            const routingEmbed = new EmbedBuilder()
                .setColor(COLORS.warning)
                .setTitle('💼 Select Assignment Manager')
                .setDescription(`Metrics captured! (Job Code: \`${generatedCode}\`). Choose the designated project manager below to handle onboarding routing.`);

            const managerSelect = new UserSelectMenuBuilder()
                .setCustomId(`routepm_${cacheKey}`)
                .setPlaceholder('Choose a manager...')
                .setMinValues(1)
                .setMaxValues(1);

            const row = new ActionRowBuilder().addComponents(managerSelect);
            await interaction.editReply({ embeds: [routingEmbed], components: [row] });
            return;
        }
    }

    // ----------------------------------------
    // HANDLE PROJECT MANAGER USER DROP MENUS
    // ----------------------------------------
    if (interaction.isUserSelectMenu()) {
        if (interaction.customId.startsWith('routepm_')) {
            await interaction.deferUpdate();
            const cacheKey = interaction.customId.split('_')[1];
            const selectedManager = interaction.users.first();

            const hireData = SYSTEM_CACHE.pendingHires[cacheKey];
            if (!hireData) return;

            let targetUser;
            try { targetUser = await client.users.fetch(hireData.targetId); } catch { return; }

            if (!hireData.isManual && SYSTEM_CACHE.activeInterviews > 0) {
                SYSTEM_CACHE.activeInterviews--;
            }

            const fineAuditCardEmbed = new EmbedBuilder()
                .setColor(COLORS.success)
                .setTitle('🟢 Roster File Insertion Executed')
                .setDescription('`⚡ Transferring operational system permissions cards...`')
                .setThumbnail(targetUser.displayAvatarURL({ dynamic: true }))
                .addFields(
                    { name: '👤 Employed Talent', value: `${targetUser}\n(${targetUser.username})`, inline: true },
                    { name: '🛠️ Core Role', value: `\`${hireData.role.toUpperCase()}\``, inline: true },
                    { name: '🏷️ Assigned Code', value: `\`${hireData.jobCode}\``, inline: true },
                    { name: '📊 Matrix Output', value: `\`${hireData.passRate}\``, inline: true }
                );

            const logsChan = await client.channels.fetch(CONFIG.HIRED_CHANNEL_ID).catch(() => null);
            if (logsChan) await logsChan.send({ embeds: [fineAuditCardEmbed] });

            try { await selectedManager.send({ embeds: [fineAuditCardEmbed] }); } catch {}

            try {
                const offerEmbed = new EmbedBuilder()
                    .setColor(COLORS.success)
                    .setTitle('🎉 Certamen Studios — Application Accepted!')
                    .setDescription(`Hello **${targetUser.displayName}**,\n\nWe are absolutely thrilled to inform you that you have been **ACCEPTED** into Certamen Studios for the position of **${hireData.role.toUpperCase()}**! A manager (<@${selectedManager.id}>) will reach out shortly.`);
                await targetUser.send({ embeds: [offerEmbed] });
            } catch {}

            if (!hireData.isManual && hireData.channel) {
                await hireData.channel.send({ content: `🏁 **File finalized.** Job code generated [\`${hireData.jobCode}\`] and dispatched to manager.` });
                await hireData.channel.setName(`[HIRED] ${targetUser.username}`);
                await hireData.channel.setArchived(true);
            }
            
            delete SYSTEM_CACHE.pendingHires[cacheKey];
            await interaction.message.edit({ content: '📨 **Success:** Onboarding profile compiled and dispatched safely.', embeds: [], components: [] });
            return;
        }
    }
});

// ============================================
//       MESSAGE INTERCEPT ENGINE (THE BRIDGE)
// ============================================
client.on('messageCreate', async message => {
    if (message.author.bot) return;

    // ----------------------------------------
    // SERVER-SIDE TUNNEL TRANSFERS (OUTBOUND)
    // ----------------------------------------
    if (message.channel.isThread()) {
        const startMessage = await message.channel.fetchStarterMessage().catch(() => null);
        if (!startMessage || !startMessage.embeds[0]) return;

        // Verify this thread belongs to either our standard Interview Forum or our Custom DM Forum
        if (message.channel.parent?.id !== CONFIG.FORUM_CHANNEL_ID && message.channel.parent?.id !== CONFIG.DM_FORUM_CHANNEL_ID) return;

        const idField = startMessage.embeds[0].fields.find(f => f.name === '🆔 Core System ID');
        if (!idField) return;

        const targetUserId = idField.value.replace(/`/g, '');

        try {
            const targetUser = await client.users.fetch(targetUserId);
            
            const outboundEmbed = new EmbedBuilder()
                .setColor(COLORS.neutral)
                .setAuthor({ name: `Message from Arya (HR Representative)`, iconURL: message.author.displayAvatarURL() })
                .setDescription(message.content)
                .setTimestamp();

            if (message.attachments.size > 0) {
                const firstAttach = message.attachments.first();
                if (firstAttach.contentType?.startsWith('image/')) outboundEmbed.setImage(firstAttach.url);
            }

            await targetUser.send({ embeds: [outboundEmbed] });
            await message.react('✉️').catch(() => {});
        } catch (error) {
            await message.reply({ content: '❌ **Message Dropped:** DMs closed or bot blocked.' });
        }
        return;
    }

    // ----------------------------------------
    // DIRECT MESSAGE INTERCEPT CONTROLLER (INBOUND)
    // ----------------------------------------
    if (message.channel.type === ChannelType.DM) {
        try {
            const guilds = await client.guilds.fetch();
            const targetedGuild = await guilds.get(CONFIG.GUILD_ID)?.fetch();
            if (!targetedGuild) return;

            const activeThreadsData = await targetedGuild.channels.fetchActiveThreads();
            let matchedThread = null;

            for (const [_, thread] of activeThreadsData.threads) {
                // Only read active tracking streams belonging to our interview forum or DM session forum
                if (thread.parent?.id !== CONFIG.FORUM_CHANNEL_ID && thread.parent?.id !== CONFIG.DM_FORUM_CHANNEL_ID) continue;

                const starter = await thread.fetchStarterMessage().catch(() => null);
                if (starter && starter.embeds[0]) {
                    const idField = starter.embeds[0].fields.find(f => f.name === '🆔 Core System ID');
                    if (idField && idField.value.replace(/`/g, '') === message.author.id) {
                        matchedThread = thread;
                        break;
                    }
                }
            }

            if (matchedThread) {
                const incomingEmbed = new EmbedBuilder()
                    .setColor(COLORS.success)
                    .setAuthor({ name: `${message.author.username} (Response Received)`, iconURL: message.author.displayAvatarURL() })
                    .setDescription(message.content)
                    .setTimestamp();

                if (message.attachments.size > 0) {
                    const incomingAttach = message.attachments.first();
                    if (incomingAttach.contentType?.startsWith('image/')) incomingEmbed.setImage(incomingAttach.url);
                }

                await matchedThread.send({ embeds: [incomingEmbed] });
                await message.react('✅').catch(() => {});
            }
        } catch (err) {
            console.error('Error handling incoming DM packet:', err);
        }
    }
});

client.login(process.env.TOKEN);